import { AfterViewInit, Component, ViewChild, ViewEncapsulation  } from '@angular/core';

import { MatPaginator } from '@angular/material/paginator';
import { CompanyBaseReportFilterComponent } from 'src/app/components/modal/company-base-report-filter/company-base-report-filter.component';
import {MatTableDataSource} from '@angular/material/table';

import { MatDialog } from '@angular/material/dialog';
@Component({
  selector: 'app-company-base-report-listing',
  templateUrl: './company-base-report-listing.component.html',
  styleUrls: ['./company-base-report-listing.component.scss']
})


  export class CompanyBaseReportListingComponent implements AfterViewInit {
    constructor(public dialog: MatDialog) {}
  
    openDialog() {
      this.dialog.open(CompanyBaseReportFilterComponent, {
        width: '850px',
        data: {}
      });
    }

  ngOnInit(): void {
  }

  displayedColumns: string[] = ['companyName', 'SourceOperator', 'designationOperator','smsMethod', 'osType','smsEng','smsZawgyi','smsUnicode','sendType','frequency','mobileCount','price','frequencyCount','NoOfMessage','totalMessage','okId','totalAmount','refundId','refundReason','refendStatus','refendAmount','fromDate','toDate','fromTime','toTime','action'];
  dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);

  @ViewChild(MatPaginator) paginator!: MatPaginator;

  ngAfterViewInit() {
    this.dataSource.paginator = this.paginator;
  }

}
export interface PeriodicElement {
  companyName:string;
  SourceOperator: string;
  designationOperator: string;
  smsMethod: string;
  osType:string;
  smsEng:string;
  smsZawgyi: string;
  smsUnicode: string;
  sendType: string;
  frequency:string;
  mobileCount: string;
  price:string;
  frequencyCount:string;
  NoOfMessage:string;
  totalMessage:string;
  okId:string;
  totalAmount:string;
  refundId:string;
  refundReason:string;
  refendStatus:string;
  refendAmount:string;
  fromDate:string;
  toDate:string;
  fromTime:string;
  toTime:string;
  action: string;

}


const ELEMENT_DATA: PeriodicElement[] = [
  {companyName:'GAT',
  SourceOperator:'MPT',
  designationOperator:'MPT',
  smsMethod:'On Net',
  osType:'Both',
  smsEng:'Hi, Mingalar Par',
  smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
  smsUnicode:'SMS Content Unicode',
  sendType:'Immediately',
  frequency:'-',
  mobileCount:'2000',
  price :'7',
  frequencyCount:'-',
  NoOfMessage:'-',
  totalMessage:'20,000',
  okId:'1063010697',
  totalAmount:'140,000',
  refundId:'-',
  refundReason:'-',
  refendStatus:'-',
  refendAmount:'-',
  fromDate:'Fri,12-Jun-2021',
  toDate:'Mon,12-Sep-2021',
  fromTime:'12:10:20',toTime:'18:00:00',
  action:'assets/img/Icon/Eye.svg'
},

{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},


{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},


{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},


{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},


{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},

{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},

{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},

{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},
{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},
{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},
{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},
{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},
{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},
{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},
{companyName:'GAT',
SourceOperator:'MPT',
designationOperator:'MPT',
smsMethod:'On Net',
osType:'Both',
smsEng:'Hi, Mingalar Par',
smsZawgyi:'ဟိုင်း, မင်္ဂလာပါ',
smsUnicode:'SMS Content Unicode',
sendType:'Immediately',
frequency:'-',
mobileCount:'2000',
price :'7',
frequencyCount:'-',
NoOfMessage:'-',
totalMessage:'20,000',
okId:'1063010697',
totalAmount:'140,000',
refundId:'-',
refundReason:'-',
refendStatus:'-',
refendAmount:'-',
fromDate:'Fri,12-Jun-2021',
toDate:'Mon,12-Sep-2021',
fromTime:'12:10:20',toTime:'18:00:00',
action:'assets/img/Icon/Eye.svg'
},

    
];

